In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


In [3]:
if torch.cuda.is_available():
  print("GPU is available")
else:
  print("GPU is not available, using CPU")

GPU is available


## **Creating a Tensor**

In [4]:
torch.empty(2,3)

tensor([[   0.0000,    0.0000,    0.0000],
        [   0.0000, 4246.3672,    0.0000]])

In [5]:
a = torch.empty(2,3)

type(a)

torch.Tensor

In [6]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.rand(2,3)

tensor([[0.0180, 0.1768, 0.5660],
        [0.6822, 0.3985, 0.2059]])

In [9]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [10]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [11]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [12]:
torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [14]:
torch.linspace(0,10,15)

tensor([ 0.0000,  0.7143,  1.4286,  2.1429,  2.8571,  3.5714,  4.2857,  5.0000,
         5.7143,  6.4286,  7.1429,  7.8571,  8.5714,  9.2857, 10.0000])

In [15]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [16]:
torch.full((3,3),69)

tensor([[69, 69, 69],
        [69, 69, 69],
        [69, 69, 69]])

## **Tensor Shapes**

In [17]:
x = torch.tensor([[1,2,3],[3,4,5]])
x

tensor([[1, 2, 3],
        [3, 4, 5]])

In [18]:
x.shape

torch.Size([2, 3])

In [19]:
torch.empty_like(x)

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 7377284542206731362]])

In [20]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [22]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

## **Tensor Data Types**

In [23]:
x.dtype

torch.int64

In [24]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [25]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [3., 4., 5.]])

In [26]:
x.dtype

torch.int64

## **Mathematical Operations**

### **Scalar Operations**

In [27]:
x = torch.rand(2,2)
x

tensor([[0.8694, 0.5677],
        [0.7411, 0.4294]])

In [28]:
x + 2

tensor([[2.8694, 2.5677],
        [2.7411, 2.4294]])

In [29]:
x - 2

tensor([[-1.1306, -1.4323],
        [-1.2589, -1.5706]])

In [30]:
x / 50

tensor([[0.0174, 0.0114],
        [0.0148, 0.0086]])

In [31]:
x * 800

tensor([[695.5236, 454.1722],
        [592.8752, 343.5236]])

In [32]:
(x * 800) // 20

tensor([[34., 22.],
        [29., 17.]])

In [33]:
((x * 800) // 20) % 2

tensor([[0., 0.],
        [1., 1.]])

In [34]:
x**2

tensor([[0.7559, 0.3223],
        [0.5492, 0.1844]])

### **Element-wise Operations**

In [35]:
a = torch.rand(2,2)
b = torch.rand(2,2)

In [36]:
a + b

tensor([[1.1551, 1.0153],
        [0.5635, 1.4591]])

In [37]:
a - b

tensor([[ 0.6158,  0.1325],
        [-0.0303, -0.2042]])

In [38]:
a * b

tensor([[0.2387, 0.2533],
        [0.0792, 0.5218]])

In [39]:
a / b

tensor([[3.2839, 1.3003],
        [0.8978, 0.7544]])

In [40]:
a ** b

tensor([[0.9677, 0.7826],
        [0.6753, 0.6787]])

In [41]:
c = torch.tensor([1,2,-3,-4])

In [42]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [43]:
torch.neg(c)

tensor([-1, -2,  3,  4])

In [44]:
torch.round(a)

tensor([[1., 1.],
        [0., 1.]])

In [45]:
torch.ceil(b)

tensor([[1., 1.],
        [1., 1.]])

In [46]:
torch.floor(a)

tensor([[0., 0.],
        [0., 0.]])

In [47]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [48]:
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [49]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[9., 3., 1.],
        [9., 7., 9.]])

In [50]:
torch.sum(e)

tensor(38.)

In [51]:
torch.sum(e,dim=0)

tensor([18., 10., 10.])

In [52]:
torch.sum(e,dim=1)

tensor([13., 25.])

In [53]:
torch.mean(e)

tensor(6.3333)

In [54]:
torch.mean(e,dim=0)

tensor([9., 5., 5.])

In [55]:
torch.mean(e,dim=1)

tensor([4.3333, 8.3333])

In [56]:
torch.median(e)

tensor(7.)

In [57]:
torch.min(e)

tensor(1.)

In [58]:
torch.max(e)

tensor(9.)

In [59]:
torch.prod(e)

tensor(15309.)

In [60]:
torch.std(e)

tensor(3.5024)

In [61]:
torch.var(e)

tensor(12.2667)

In [62]:
torch.argmax(e)

tensor(0)

In [63]:
torch.argmin(e)

tensor(2)

## **Matrix Operations**

In [64]:
f = torch.randint(size=(2,3),low=0,high=10)
g = torch.randint(size=(3,2),low=0,high=10)

print(g)
print(f)

tensor([[9, 6],
        [2, 0],
        [6, 2]])
tensor([[2, 0, 5],
        [9, 3, 4]])


In [65]:
torch.matmul(f,g)

tensor([[ 48,  22],
        [111,  62]])

In [66]:
v1 = torch.tensor([1,2])
v2 = torch.tensor([3,4])

In [67]:
torch.dot(v1,v2)

tensor(11)

In [68]:
torch.transpose(f,0,1)

tensor([[2, 9],
        [0, 3],
        [5, 4]])

In [69]:
torch.det(a)

tensor(0.4026)

In [70]:
torch.inverse(a)

tensor([[ 1.5586, -1.4256],
        [-0.6622,  2.1994]])

## **Comparison Operations**

In [71]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low=0,high=10)

In [72]:
i

tensor([[7, 9, 7],
        [3, 3, 4]])

In [73]:
j

tensor([[3, 7, 0],
        [9, 0, 9]])

In [74]:
i > j

tensor([[ True,  True,  True],
        [False,  True, False]])

In [75]:
i == j

tensor([[False, False, False],
        [False, False, False]])

## **Special Functions**

In [76]:
k = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[6., 9., 5.],
        [4., 8., 8.]])

In [77]:
torch.log(k)

tensor([[1.7918, 2.1972, 1.6094],
        [1.3863, 2.0794, 2.0794]])

In [78]:
torch.exp(k)

tensor([[ 403.4288, 8103.0840,  148.4132],
        [  54.5981, 2980.9580, 2980.9580]])

In [79]:
torch.sqrt(k)

tensor([[2.4495, 3.0000, 2.2361],
        [2.0000, 2.8284, 2.8284]])

In [80]:
torch.sigmoid(k)

tensor([[0.9975, 0.9999, 0.9933],
        [0.9820, 0.9997, 0.9997]])

In [81]:
torch.softmax(k,dim=0)

tensor([[0.8808, 0.7311, 0.0474],
        [0.1192, 0.2689, 0.9526]])

In [82]:
torch.relu(k)

tensor([[6., 9., 5.],
        [4., 8., 8.]])

## **In-place Operations**

In [83]:
m = torch.rand(2,3)
n = torch.rand(2,3)

m

tensor([[0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958]])

In [84]:
n

tensor([[0.9147, 0.2036, 0.2018],
        [0.2018, 0.9497, 0.6666]])

In [85]:
m.add(n)

tensor([[1.4462, 0.3624, 0.8560],
        [0.5296, 1.6029, 1.0625]])

In [86]:
m

tensor([[0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958]])

In [87]:
m.add_(n)

tensor([[1.4462, 0.3624, 0.8560],
        [0.5296, 1.6029, 1.0625]])

In [88]:
m

tensor([[1.4462, 0.3624, 0.8560],
        [0.5296, 1.6029, 1.0625]])

## **Copying a Tensor**

In [89]:
a = torch.rand(2,3)
a

tensor([[0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025]])

In [90]:
b = a.clone()

In [91]:
b

tensor([[0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025]])

## **Tensor Operations on GPU**

In [92]:
torch.cuda.is_available()

True

In [93]:
device = torch.device('cuda')

In [94]:
torch.rand((2,3),device=device)

tensor([[0.6130, 0.0101, 0.3984],
        [0.0403, 0.1563, 0.4825]], device='cuda:0')

In [97]:
x = torch.rand(2,3)
x

tensor([[0.8035, 0.3813, 0.7860],
        [0.1115, 0.2477, 0.6524]])

In [98]:
x.to(device)

tensor([[0.8035, 0.3813, 0.7860],
        [0.1115, 0.2477, 0.6524]], device='cuda:0')

## **Reshaping Tensors**

In [99]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [100]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [101]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [102]:
b = torch.rand(2,3,4)
b

tensor([[[0.6057, 0.3725, 0.7980, 0.8399],
         [0.1374, 0.2331, 0.9578, 0.3313],
         [0.3227, 0.0162, 0.2137, 0.6249]],

        [[0.4340, 0.1371, 0.5117, 0.1585],
         [0.0758, 0.2247, 0.0624, 0.1816],
         [0.9998, 0.5944, 0.6541, 0.0337]]])

In [104]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [106]:
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [107]:
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])